### ISSUE TITLE
ReorganizeCurrentFile from another extension

### ISSUE THREAD

**Issue by lksg** [waldo1001/crs-al-language-extension#126]
Hi,

I'm trying to call ReorganizeCurrentFile from my extension like so:
vscode.commands.executeCommand("crs.ReorganizeCurrentFile");
This works well for RenameCurrentFile but with ReorganizeCurrentFile I get this output:

```
Running: ReorganizeCurrentFile
Done: ReorganizeCurrentFile
CRSFunctions.js:106
rejected promise not handled within 1 second: TypeError: Cannot read property 'uri' of undefined
extensionHostProcess.js:749
stack trace: TypeError: Cannot read property 'uri' of undefined
	at Function.ReorganizeFile (C:\Users\lknollmeyer\.vscode\extensions\waldo.crs-al-language-extension-1.1.9\out\WorkspaceFiles.js:80:87)
	at ReorganizeCurrentFile.vscode.window.activeTextEditor.document.save.then.saved (C:\Users\lknollmeyer\.vscode\extensions\waldo.crs-al-language-extension-1.1.9\out\CRSFunctions.js:103:59)
```

I would love to be able to call this function to help tidy up the workspace after .al-filecreation.

Best Regards Leon

**Comment by waldo1001** [comment]
Hi,

am I getting this right:
You are building your own VSCode Extension, and try to call commands from my extension?

Can you call the function manually? I would like to be able to repro this.  Is there any repro scenario I could simulate the above?

**Comment by lksg** [comment]
Hi waldo,

I threw together a tiny extension that creates a new .al file in the workspace and then tries to reorganize it: https://github.com/lksg/CRS-bug-test

With this you should be able to quickly reproduce the problem.
The error does not occure when I call the CRS function manually.

Regards
