### ISSUE TITLE
Reorganize All Files - Error: Cannot read property '1' of null

### ISSUE THREAD

**Issue by tso-sm** [waldo1001/crs-al-language-extension#137]
Hi, 
I have a AL-Project and get following error:

Error: Cannot read property '1' of null at 'CRS: Reorganize - All Files'

Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Datum: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Windows_NT x64 10.0.18362

`
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'document' of undefined
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'document' of undefined
	at Object.toggleRunObjectFromStatusBar (c:\Users\smeyer\.vscode\extensions\waldo.crs-al-language-extension-1.1.17\out\UI\CRSStatusBar.js:7:54)
	at HandleOnOpenTextDocument (c:\Users\smeyer\.vscode\extensions\waldo.crs-al-language-extension-1.1.17\out\CRSFunctions.js:149:18)
	at l.fire (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at _documentsAndEditors.onDidAddDocuments.e (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:536:225)
	at l.fire (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at f.$acceptDocumentsAndEditorsDelta (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:540:638)
	at p._doInvokeHandler (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:635:275)
	at p._invokeHandler (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:634:971)
	at p._receiveRequest (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:633:639)
	at p._receiveOneMessage (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:632:468)
	at _protocol.onMessage.e (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:691)
	at l.fire (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at _.fire (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:274)
	at e.onMessage.e (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:787:104)
	at l.fire (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at _.fire (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:274)
	at t.PersistentProtocol._receiveMessage (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:185:629)
	at _socketDisposables.push._socketReader.onMessage.e (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:824)
	at l.fire (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at p.acceptChunk (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:588)
	at _register._socket.onData.e (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:177:958)
	at Socket.t (c:\Users\smeyer\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:68)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
notificationsAlerts.ts:40 Cannot read property '1' of null
`
![2019-10-16 11_02_25-Window](https://user-images.githubusercontent.com/55545401/66905504-43d4cb80-f006-11e9-80b2-050fa34d636a.png)

**Comment by waldo1001** [comment]
I will need to see the repo and files in order to investigate.  But to be honest, it is not really recommended to use the "reorganize" as this will create folders by object type, which is an old way of organizing objects...
